services:
  - type: web
    name: fastapi-supabase-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    ports:
      - port: 10000
        protocol: TCP 